services: 
  server:
    build: 
      context: ./server
    ports:
      - "{SERVER_PORT}:5000"
    volumes:
      - ./server/uploads:/app/uploads
      - ./server/imgs:/app/imgs


  client:
    build: 
      context: ./client
    ports:
      - "{CLIENT_PORT}:80"


