version: '3'
services: 
  server:
    build: 
      context: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server/uploads:/app/uploads
      - ./server/imgs:/app/imgs


  client:
    build: 
      context: ./client
    ports:
      - "80:80"


