name: Github Actions Demo
run-name: testing out Github Actions
on: 
  push:
  workflow_dispatch:
jobs:
  Explore-Github-Actions:
    runs-on: ubuntu-latest
    steps:
     - run: echo "Automatically triggered by a ${{ github.event_name }} event."
     - run: echo "Now running on a ${{ runner.os }} server hosted by Github!"
     - run: echo "On branch ${{ github.ref }} - repo ${{ github.repository }}."
     - name: Check out repository code
       uses: actions/checkout@v3
     - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
     - run: echo "The workflow is now ready to test your code on the runner."
     - name: List files in the repository
       run: |
         ls ${{ github.workspace }}
     - run: echo "This job's status is ${{ job.status }}."
